execute pathogen#infect()
syntax on
filetype plugin indent on

syntax enable
set background=dark
colorscheme desert
call togglebg#map("<F5>")
set pastetoggle=<F10>

map T :TaskList<CR>
map P :TlistToggle<CR>

nnoremap <C-Left> :tabprevious<CR>
nnoremap <C-Right> :tabnext<CR>

autocmd FileType python set omnifunc=pythoncomplete#Complete
set laststatus=2
set smarttab
set number
set paste
set list
set expandtab
set textwidth=79
set tabstop=8
set softtabstop=4
set shiftwidth=4
set autoindent
:syntax on
cnoreabbrev <expr> W ((getcmdtype() is# ':' && getcmdline() is# 'W')?('w'):('W'))
